language: php
php:
  - "5.6"
  - "7.1"

install:
  - composer install

script:
  - vendor/bin/phpunit --debug --exclude-group db --coverage-clover ./clover.xml
  - php coverage-checker.php clover.xml 10
